# --- !Ups

create table "user" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "first_name" varchar not null,
  "last_name" varchar not null
);

create table "wish_list" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "userId" number not null,
  "productId" number not null
);

# --- !Downs

drop table "user" if exists;
drop table "wish_list" if exists;
